---
sidebar: sidebar 
permalink: concept-licensing-charging.html 
keywords: capacity-based license charging, consumption for licenses, pricing for licenses, CVO licensing, CVO charging 
summary: 熟悉容量型授權的收費，使用模式，定價與組態。 
---
= 深入瞭解 Cloud Volumes ONTAP 容量型授權
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您應該熟悉容量型授權的收費與容量使用



== 消費模式

下列消費模式提供容量型授權套件：

* * BYOL* ：請自帶授權（ BYOL ）。從 NetApp 購買的授權，可用於在任何雲端供應商中部署 Cloud Volumes ONTAP 。


ifdef::azure[]

+ 請注意、 BYOL 並未提供最佳化套件。

endif::azure[]

* * PAYGO* ：隨用隨付（ PAYGO ）訂閱是您雲端供應商市場的每小時訂閱。
* *年度*：雲端供應商市場的年度合約。


請注意下列事項：

* 如果您向NetApp（BYOL）購買授權、也必須向雲端供應商的市場訂閱PAYGO產品。
+
您的授權一律會先收取費用、但在下列情況下、您將會從市場的每小時費率中收取費用：

+
** 如果您超過授權容量
** 如果授權期限已到期


* 如果您有市場的年度合約、Cloud Volumes ONTAP 您所部署的_all_系統將根據該合約付費。您無法與BYOL混搭一年一度的市場合約。
* 中國地區僅支援具有BYOL的單一節點系統。




== 變更套件

部署完成後、您可以變更Cloud Volumes ONTAP 使用容量型授權的一套功能、以利執行一套功能。例如、如果您部署Cloud Volumes ONTAP 的是含有Essentials套件的功能完善的系統、則當您的業務需求改變時、可以將其變更為Professional套件。

link:task-manage-capacity-licenses.html["瞭解如何變更充電方法"]。

如需將節點型授權轉換為容量型授權的相關資訊，請參閱



== 定價與支援的組態

有關定價的詳細信息，請訪問 https://bluexp.netapp.com/pricing/["NetApp BlueXP網站"^]。

以容量為基礎的授權套件可搭配Cloud Volumes ONTAP 使用於NetApp 9.7及更新版本。



=== 儲存VM

* 額外的資料服務儲存VM（SVM）無需額外授權成本、但每個資料服務SVM的最低容量費用為4 TiB。
* 災難恢復SVM是根據已配置的容量來收費的。




=== HA 配對

對於HA配對、您只需支付節點上已配置容量的費用。您不需支付同步鏡射至合作夥伴節點的資料費用。



=== FlexClone與FlexCache 功能

* FlexClone磁碟區所使用的容量不需付費。
* 來源FlexCache 和目的地的資料不只是主要資料、而且會根據已配置的空間進行收費。




== 容量限制

有了這種授權模式、每Cloud Volumes ONTAP 個個別的支援系統都能透過磁碟和分層到物件儲存設備、支援最多2 PIB的容量。

授權本身並無最大容量限制。



== 最大系統數

透過容量型授權、Cloud Volumes ONTAP 每個NetApp帳戶最多可有20個不限數量的不二元系統。_system_是Cloud Volumes ONTAP 一個EsireHA配對、Cloud Volumes ONTAP 一個僅供支援的節點系統、或是您所建立的任何其他儲存VM。預設的儲存VM不會計入限制。此限制適用於所有授權模式。

例如、假設您有三種工作環境：

* 單一節點Cloud Volumes ONTAP 的不完整系統、只需一個儲存VM（這是部署Cloud Volumes ONTAP 時建立的預設儲存VM）
+
這種工作環境是單一系統的重要關鍵。

* 單一節點Cloud Volumes ONTAP 的不完整系統、含兩個儲存VM（預設儲存VM、加上您所建立的一個額外儲存VM）
+
此工作環境可視為兩個系統：一個用於單一節點系統、另一個用於額外的儲存VM。

* 包含三個儲存VM（預設儲存VM、加上您所建立的兩個額外儲存VM）的支援功能Cloud Volumes ONTAP
+
此工作環境可算為三個系統：一個用於HA配對、兩個用於額外的儲存VM。



總共有六個系統。之後您的帳戶就有額外14個系統的空間。

如果您的大型部署需要20個以上的系統、請聯絡您的客戶代表或銷售團隊。

https://docs.netapp.com/us-en/bluexp-setup-admin/concept-netapp-accounts.html["深入瞭解NetApp客戶"^]。



== 充電注意事項

下列詳細資料可協助您瞭解充電方式如何搭配容量型授權使用。



=== 最低收費

每個資料服務儲存VM至少要有一個主要（讀寫）磁碟區、至少需支付4 TiB的最低費用。如果主要磁碟區的總和低於4 TiB、則BlueXP會將4 TiB最低收費套用至該儲存VM。

如果您尚未配置任何磁碟區、則不適用最低收費。

對於 Essentials 套件、 4 TiB 最低容量費用不適用於僅包含次要（資料保護）磁碟區的儲存 VM 。例如、如果您的儲存虛擬機器擁有1個二線資料的TiB、則只需支付1個TiB的資料費用。對於所有其他非 Essentials 套件類型（最佳化版和專業版）、無論 Volume 類型為何、都適用 4 TiB 的最低容量充電。



=== 過度使用

如果您超過BYOL容量、或授權過期、系統會根據您的市場訂閱、按每小時費率收取超額費用。



=== Essentials套件

有了Essentials套件、您將依照部署類型（HA或單一節點）和Volume類型（主要或次要）收費。從高到低的定價順序如下： _Essentials Primary HA_ 、 _Essentials Primary Single Node_ 、 _Essentials Secondary HHA _ 和 _Essentials Secondary Single Nod_ 。或者、當您購買市場合約或接受私人優惠時、任何部署或 Volume 類型的容量費用都相同。

授權完全以在 Cloud Volumes ONTAP 系統中建立的 Volume 類型為基礎：

* Essentials 單一節點：只使用一個 ONTAP 節點、在 Cloud Volumes ONTAP 系統上建立讀寫磁碟區。
* Essentials HA ：使用兩個 ONTAP 節點的讀取 / 寫入磁碟區、可在不中斷資料存取的情況下互相容錯移轉。
* Essentials 次要單一節點：資料保護（ DP ）類型的磁碟區（通常是唯讀的 SnapMirror 或 SnapVault 目的地磁碟區）、僅使用一個 ONTAP 節點在 Cloud Volumes ONTAP 系統上建立。
+

NOTE: 如果唯讀 /DP 磁碟區變成主要磁碟區、 BlueXP  會將其視為主要資料、而充電成本則是根據磁碟區處於讀取 / 寫入模式的時間來計算。當磁碟區再次設為唯讀 /DP 時、 BlueXP  會再次將其視為次要資料、並使用數位錢包中最符合的授權進行收費。

* Essentials 次要 HA ：資料保護（ DP ）類型的磁碟區（通常是唯讀的 SnapMirror 或 SnapVault 目的地磁碟區）、是在使用兩個 ONTAP 節點的 Cloud Volumes ONTAP 系統上建立、可在不中斷資料存取的情況下互相容錯移轉。


請注意以下幾點：

* 最低費用：每個資料服務儲存 VM 至少有一個主要（讀寫）磁碟區、最低需支付 4 TiB 費用。對於 Essentials 套件、這項最低費用不適用於只有次要（資料保護）磁碟區的儲存 VM 。
* 超額：如果超過授權容量、就會以市場費率收取超額費用、並優先使用其他授權的可用容量。
* FlexClone 和 FlexCache Volumes ： FlexClone Volume 不收費。來源和目的地 FlexCache 磁碟區被視為主要資料、並根據已配置的空間收費。
* HA 配對充電：對於 HA 配對、只會對節點上的已配置容量進行充電。同步鏡射至合作夥伴節點的資料不會收費。


.BYOL
如果您向 NetApp （ BYOL ）購買 Essentials 授權、且超過該部署和 Volume 類型的授權容量、則 BlueXP 數位錢包會因價格較高的 Essentials 授權（如果您有此授權且有可用容量）而收取超額費用。這是因為我們會先使用您已購買的可用容量作為預付容量、然後再針對市場進行充電。如果您的 BYOL 授權沒有可用容量、則超出的容量將以市場隨選時數費率（ PAYGO ）收取、並將增加每月帳單的成本。

以下是範例。假設您擁有下列Essentials套件授權：

* 500 TiB _Essentials二線HA授權、擁有500 TiB的承諾容量
* 500 TiB _Essentials單一節點_授權、僅擁有100 TiB的已認可容量


另有50個TiB配置在與次要Volume的HA配對上。BlueXP 數位錢包不需向 PAYGO 收取 50 TiB 費用、而是根據 _Essentials Single Node_ 授權收取 50 TiB 超額費用。該授權的價格高於 _Essentials 次要 HHA 、但它是使用您已購買的授權、不會在您的每月帳單中增加成本。

在 BlueXP 數位錢包中、 50 TiB 將根據 _Essentials Single Nodon_ 授權收費。

以下是另一個範例。假設您擁有下列Essentials套件授權：

* 500 TiB _Essentials二線HA授權、擁有500 TiB的承諾容量
* 500 TiB _Essentials單一節點_授權、僅擁有100 TiB的已認可容量


另有 100 TiB 是在具有主要磁碟區的 HA 配對上進行佈建。您購買的授權沒有 _Essentials 主要 HA 承諾容量。_Essentials 主要 HA_ 授權的價格高於 _Essentials 主要單一節點 _ 和 _Essentials 次要 HA_ 授權。

在此範例中、 BlueXP 數位錢包會以額外 100 TiB 的市場費率收取超額費用。超額費用會顯示在您的每月帳單上。

.市場合約或私人優惠
如果您購買的 Essentials 授權屬於市場合約或私有方案的一部分、則 BYOL 邏輯將不適用、而且您必須擁有正確的使用授權類型。授權類型包括 Volume 類型（主要或次要）和部署類型（ HA 或單一節點）。

例如、假設您使用 Essentials 授權部署 Cloud Volumes ONTAP 執行個體。接著、您可以配置讀寫磁碟區（主要單一節點）和唯讀（次要單一節點）磁碟區。您的市場合約或私有方案必須包含 _Essentials 單一節點 _ 和 _Essentials 次要單一節點 _ 的容量、以涵蓋已配置的容量。任何不屬於您市場合約或私人優惠的資源配置容量、都會以隨選時數費率（ PAYGO ）收取費用、並將成本加到您的每月帳單中。
