---
sidebar: sidebar 
permalink: concept-licensing.html 
keywords: 'freemium, professional, essentials, licensing, licenses, cloud volumes ontap charging, cloud volumes ontap licenses, cloud volumes ontap licensing, cvo licenses, cvo licensing, byol, bring your own license, paygo, pay as you go, keystone flex, keystone, cloud backup, digital wallet, bluexp license conversion for node based, license end of support (EOS) node-based, end of availability (EOA) of node-based' 
summary: 有多種授權選項可供Cloud Volumes ONTAP 選擇。每個選項都能讓您選擇符合需求的組態。 
---
= 適用於本產品的授權Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
有多種授權選項可供Cloud Volumes ONTAP 選擇。每個選項都能讓您選擇符合需求的消費模式。



== 授權總覽

下列授權選項適用於新客戶。

容量型授權:: 根據Cloud Volumes ONTAP 資源配置的容量、在NetApp帳戶中支付多個支援系統的費用。包括購買附加雲端資料服務的能力。如需容量型授權使用模式的詳細資訊，請link:concept-licensing-charging.html["深入瞭解容量型授權"]參閱。
Keystone訂閱:: 以隨成長付費訂閱為基礎的服務、為高可用度（ HA ）配對提供順暢的混合雲體驗。


以下各節提供這些選項的詳細資訊。


NOTE: 若未取得授權、則無法使用授權功能。



== 容量型授權

容量型授權套件可讓您針對Cloud Volumes ONTAP 每TiB的容量付費。授權與您的NetApp帳戶相關聯、只要授權有足夠的容量可用、您就能根據授權向多個系統收取費用。

例如、您可以購買單一20 TiB授權、部署四Cloud Volumes ONTAP 個作業系統、然後將5個TiB磁碟區分配給每個系統、總共20 TiB。容量可用於Cloud Volumes ONTAP 該帳戶中部署的每個作業系統上的磁碟區。

容量型授權的形式為_package_。當您部署Cloud Volumes ONTAP 一套解決方案時、您可以根據業務需求、從多個授權套件中進行選擇。


NOTE: 雖然 BlueXP 管理的產品和服務的實際使用量和計量都是以 GiB 和 TiB 計算、但是會交替使用「 GB/GiB 」和「 TB/TiB 」這兩個詞彙。這會反映在 Cloud Marketplace 清單、價格報價、上市說明及其他支援文件中。



=== 套件

下列容量型套件可供Cloud Volumes ONTAP 使用。如需容量型授權套件的詳細資訊，請link:concept-licensing-charging.html["深入瞭解容量型授權"]參閱。

如需下列容量型套件支援的 VM 類型清單、請參閱：

ifdef::azure[]

* link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html["Azure支援的組態"^]


endif::azure[]

ifdef::gcp[]

* link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Google Cloud支援的組態"^]


endif::gcp[]



==== Freemium

NetApp Cloud Volumes ONTAP 免費提供所有的支援功能（仍需支付雲端供應商費用）。Freemium 套件具有下列特性：

* 不需要授權或合約。
* 不包括NetApp的支援。
* 每Cloud Volumes ONTAP 個系統的資源配置容量上限為500 GiB。
* 每個 NetApp 帳戶最多可搭配使用 10 個 Cloud Volumes ONTAP 系統搭配 Freemium 產品，適用於任何雲端供應商。
* 如果 Cloud Volumes ONTAP 系統的已配置容量超過 500 GiB ， BlueXP  會將系統轉換為 Essentials 套件。
+
一旦系統轉換為 Essentials 套件，即會套用至該套件link:concept-licensing-charging.html#minimum-charge["最低充電量"]。

+
已轉換為 Essentials 套件的 Cloud Volumes ONTAP 系統無法切換回 Freemium ，即使已配置的容量減至少於 500 GiB 。配置容量少於 500 GiB 的其他系統會留在 Freemium （只要使用 Freemium 產品進行部署）。





==== 基礎知識

您可以在多種不同組態中依容量付費：

* 選擇Cloud Volumes ONTAP 您的需求組態：
+
** 單一節點或HA系統
** 用於災難恢復（DR）的檔案與區塊儲存或次要資料


* 以額外成本附加任何NetApp的雲端資料服務




==== 最佳化

單獨支付已配置的容量和I/O作業費用。

* 單一節點或HA Cloud Volumes ONTAP
* 充電是以兩個成本元件為基礎：儲存與使用（ I/O ）。
+
與資料複寫（ SnapMirror ）、備份（ SnapVault ）或 NDMP 相關的 I/O 將不會收取費用。



ifdef::azure[]

* 您可在Azure Marketplace以隨用隨付方案或年度合約形式取得


endif::azure[]

ifdef::gcp[]

* 可在Google Cloud Marketplace以隨用隨付方案或年度合約形式提供


endif::gcp[]

* 以額外成本附加任何NetApp的雲端資料服務




==== 專業人員

以容量支付Cloud Volumes ONTAP 任何類型的不受限制的還原組態。

* 提供Cloud Volumes ONTAP 任何功能組態的授權
+
單一節點或HA、以相同速率為主要和次要磁碟區充電

* 包括使用 BlueXP 備份與還原的不限數量的 Volume 備份、但僅適用於使用專業版套件的 Cloud Volumes ONTAP 系統。
+

NOTE: BlueXP  備份與還原需要付費（ PAYGO ）訂閱，但使用此服務不會產生任何費用。如需設定 BlueXP  備份與還原授權的詳細資訊，請 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-licensing-cloud-backup.html["設定 BlueXP 備份與還原的授權"^]參閱。

* 以額外成本附加任何NetApp的雲端資料服務




=== 容量型授權的可用度

Cloud Volumes ONTAP 系統的 PAYGO 和 BYOL 授權的可用性，需要 BlueXP  Connector 正常運作。如需詳細資訊、請 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html#impact-on-cloud-volumes-ontap["深入瞭解連接器"^]參閱。



=== 如何開始使用

瞭解如何開始使用容量型授權：

ifdef::aws[]

* link:task-set-up-licensing-aws.html["在Cloud Volumes ONTAP AWS中設定適用於此功能的授權"]


endif::aws[]

ifdef::azure[]

* link:task-set-up-licensing-azure.html["在Cloud Volumes ONTAP Azure中設定for NetApp的授權"]


endif::azure[]

ifdef::gcp[]

* link:task-set-up-licensing-google.html["在Cloud Volumes ONTAP Google Cloud中設定適用於此技術的授權"]


endif::gcp[]



== Keystone訂閱

以隨成長付費訂閱為基礎的服務、可為偏好營運成本使用模式的使用者、提供無縫的混合雲體驗、以供預先支付資本支出或租賃之用。

充電是根據 Keystone 訂閱中一或多個 Cloud Volumes ONTAP HA 配對的承諾容量大小而定。

系統會定期彙總每個 Volume 的已配置容量、並將其與 Keystone 訂閱上的已認可容量進行比較、而任何超額資料都會在 Keystone 訂閱上以暴增方式收費。

link:https://docs.netapp.com/us-en/keystone-staas/index.html["深入瞭解 NetApp Keystone"^]。



=== 支援的組態

HA 配對支援 Keystone 訂閱。目前單一節點系統不支援此授權選項。



=== 容量限制

每Cloud Volumes ONTAP 個個別的支援透過磁碟和分層至物件儲存設備、最多可支援2個PIB容量。



=== 如何開始使用

瞭解如何開始使用 Keystone 訂閱：

ifdef::aws[]

* link:task-set-up-licensing-aws.html["在Cloud Volumes ONTAP AWS中設定適用於此功能的授權"]


endif::aws[]

ifdef::azure[]

* link:task-set-up-licensing-azure.html["在Cloud Volumes ONTAP Azure中設定for NetApp的授權"]


endif::azure[]

ifdef::gcp[]

* link:task-set-up-licensing-google.html["在Cloud Volumes ONTAP Google Cloud中設定適用於此技術的授權"]


endif::gcp[]



== 節點型授權

節點型授權是前一代的授權模式、可讓您依Cloud Volumes ONTAP 節點授權使用。此授權模式不適用於新客戶。副節點充電已由上述的副容量充電方法取代。

NetApp 已規劃終止供應（ EOA ），並支援（ EOS ）節點型授權。在 EOA 和 EOS 之後，節點型授權將需要轉換為容量型授權。

如需相關資訊、請 https://mysupport.netapp.com/info/communications/CPC-00589.html["客戶公報： CPS-00589"^]參閱。



=== 終止節點型授權的可用性

自 2024 年 11 月 11 日起，節點型授權的有限可用度已終止。節點型授權支援將於 2024 年 12 月 31 日終止。

如果您的有效節點型合約超過 EOA 日期，您可以繼續使用授權，直到合約到期為止。合約到期後，必須轉換至容量型授權模式。如果您沒有 Cloud Volumes ONTAP 節點的長期合約，請務必在 EOS 日期之前規劃您的轉換。

從下表中深入瞭解每種授權類型及 EOA 對其的影響：

[cols="2*"]
|===
| 授權類型 | EOA 之後的影響 


 a| 
透過自帶授權（ BYOL ）購買的有效節點型授權
 a| 
授權在到期前仍有效。現有未使用的節點型授權可用於部署新的 Cloud Volumes ONTAP 系統。



 a| 
透過 BYOL 購買的過期節點型授權
 a| 
您將無權使用此授權部署新的 Cloud Volumes ONTAP 系統。現有系統可能會繼續運作，但在 EOS 日期後，您將不會收到任何系統支援或更新。



 a| 
使用 PAYGO 訂閱的有效節點型授權
 a| 
在 EOS 日期之後，將停止接收 NetApp 支援，直到您轉換至容量型授權為止。

|===
.排除
NetApp 瞭解某些情況需要特別考量，而節點型授權的 EOA 和 EOS 不適用於下列情況：

* 美國公家機關客戶
* 以私有模式部署
* 在 AWS 中部署 Cloud Volumes ONTAP 的中國地區


針對這些特定案例， NetApp 將提供支援，以因應合約義務和營運需求，滿足獨特的授權要求。


NOTE: 即使在這些案例中，新的節點型授權和授權續約自核准日期起，最長可有效一年。



== 授權轉換

BlueXP  可透過授權轉換工具，將節點型授權無縫轉換為容量。如需節點型授權的 EOA 相關資訊，請link:concept-licensing.html#end-of-availability-of-node-based-licenses["終止節點型授權的可用性"]參閱。

在轉換之前，最好先熟悉兩種授權模式之間的差異。節點型授權包括每個 ONTAP 執行個體的固定容量，因此可能會限制靈活度。另一方面，容量型授權則允許跨多個執行個體共用儲存池，提供更高的靈活度，最佳化資源使用率，並降低重新分配工作負載時的財務處罰可能性。容量型充電功能可根據不斷變化的儲存需求進行無縫調整。

若要瞭解如何執行此轉換，請參閱link:task-convert-node-capacity.html["將 Cloud Volumes ONTAP 節點型授權轉換為容量型授權"]。


NOTE: 不支援將系統從容量型轉換為節點型授權。
