---
sidebar: sidebar 
permalink: task-saz-feature.html 
keywords: Microsoft Azure feature, HA in SAZ, single availability zone, Azure feature, Virtual Machine Scale Sets in Flexible mode 
summary: 啟用此 Microsoft Azure 功能、即可在 SAZ 中部署 HA 。 
---
= 為單一可用性區域啟用 VMOrchestratorZonalMultiFD
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
若要在本機備援儲存設備（ LRS ）單一可用性區域中部署 VM 執行個體 `Microsoft.Compute/VMOrchestratorZonalMultiFD`、您應該啟動 Microsoft 功能以供訂閱之用。在 HA 模式中、此功能可協助您在相同可用性區域的個別故障網域中部署節點。

除非您啟動此功能、否則不會進行分區部署、而先前的 LRS 非分區部署也會生效。

有關在單一可用性區域中部署 VM 的資訊，請參閱link:concept-ha-azure.html["Azure 中的高可用度配對"]。

以「擁有者」 Privileges 的使用者身分執行下列步驟：

.步驟
. 從 Azure 入口網站存取 Azure Cloud Shell 。如需相關資訊、請 https://learn.microsoft.com/en-us/azure/cloud-shell/get-started/["Microsoft Azure 文件：開始使用 Azure Cloud Shell"^]參閱。
.  `Microsoft.Compute/VMOrchestratorZonalMultiFD`執行下列命令以註冊此功能：
+
[]
====
AZ 帳戶集 -s <Azure_subscription_name_or_ID> _ AZ 功能登錄名稱 VMOrchestratorZonalMultiFD --namespace Microsoft.Compute

====
. 驗證登錄狀態和輸出範例：
+
[]
====
AZ 功能顯示 -n VMOrchestratorZonalMultiFD --namespace Microsoft.Compute { "id" ： <ID> "/sitations/_provider/Microsoft.Features/provider/Microsoft.Compute/features/VMOrchestratorZonalMultiFD" 、 "name" ： "Microsoft.Compute/VMOrchestratorZonalMultiFD" 、 "properties" ： { "state ： "Registered " } 、 "type" ： "Microsoft.Features/provider/features" }

====

