---
sidebar: sidebar 
permalink: task-managing-svms-azure.html 
keywords: storage virtual machine, vserver, svm, storage vm, supported number, number supported 
summary: 儲存虛擬機器是 ONTAP 執行於支援內部的虛擬機器、可為您的用戶端提供儲存與資料服務。您可能知道這是 SVM 或 Vserver 。根據預設、系統會設定一個儲存 VM 、但部分組態會支援額外的儲存 VM 。 Cloud Volumes ONTAP 
---
= 管理 Azure 中 Cloud Volumes ONTAP 的資料服務儲存 VM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
儲存虛擬機器是 ONTAP 執行於支援內部的虛擬機器、可為您的用戶端提供儲存與資料服務。您可能知道這是 _SVM_ 或 _vserver_ 。根據預設， Cloud Volumes ONTAP 設有一個儲存 VM ，但在 Azure 中執行 Cloud Volumes ONTAP 時，您可以建立其他儲存 VM 。

若要在 Azure 中建立及管理其他資料服務儲存 VM ，您應該使用 BlueXP  API 。這是因為 API 會自動化建立儲存 VM 和設定所需網路介面的程序。建立儲存 VM 時， BlueXP  會設定所需的 LIF 服務，以及從儲存 VM 輸出 SMB/CIFS 通訊所需的 iSCSI LIF 。

如需執行 Cloud Volumes ONTAP API 呼叫的相關資訊，請 https://docs.netapp.com/us-en/bluexp-automation/cm/your_api_call.html#step-1-select-the-identifie["您的第一個API呼叫"^]參閱。



== 支援的儲存 VM 數量

從 Cloud Volumes ONTAP 9.0.0 開始，根據您的授權，特定組態可支援多個儲存 VM 。請參閱 https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limits-azure.html["發行說明 Cloud Volumes ONTAP"^]，確認您的 Cloud Volumes ONTAP 版本支援的儲存 VM 數量。

早於 9.9.0 的所有 Cloud Volumes ONTAP 版本都支援一個資料服務儲存 VM ，以及一個目的地儲存 VM ，用於災難恢復。如果來源儲存VM發生中斷、您可以啟動目的地儲存VM進行資料存取。



== 建立儲存VM

根據您的組態和授權類型，您可以使用 BlueXP  API ，在單一節點系統或高可用度（ HA ）組態中建立多個儲存 VM 。

.關於這項工作
當您使用 API 建立儲存 VM ，以及設定所需的網路介面時， BlueXP  也會從 NAS 資料 LIF 移除下列服務，並將這些服務新增至用於輸出管理連線的 iSCSI 資料 LIF ，藉此修改 `default-data-files`資料儲存 VM 上的原則：

* `data-fpolicy-client`
* `management-ad-client`
* `management-dns-client`
* `management-ldap-client`
* `management-nis-client`


.開始之前
Connector 需要特定權限才能為 Cloud Volumes ONTAP 建立儲存 VM 。所需的權限包含在 https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-azure.html["NetApp 提供的原則"^]中。



=== 單一節點系統

使用下列 API 呼叫在單一節點系統上建立儲存 VM 。

`POST /azure/vsa/working-environments/{workingEnvironmentId}/svm`

在要求主體中包含下列參數：

[source, json]
----
{ "svmName": "myNewSvm1"
   "svmPassword": "optional, the API takes the cluster password if not provided"
   "mgmtLif": "optional, to create an additional management LIF, if you want to use the storage VM for management purposes"}
----


=== HA配對

使用下列 API 呼叫在 HA 配對上建立儲存 VM ：

`POST /azure/ha/working-environments/{workingEnvironmentId}/svm`

在要求主體中包含下列參數：

[source, json]
----
{ "svmName": "NewSvmName"
   "svmPassword": "optional value, the API takes the cluster password if not provided"
   "mgmtLif": "optional value, to create an additional management LIF, if you want to use the storage VM for management purposes"}
----


== 在單一節點系統和 HA 配對上管理儲存 VM

使用 BlueXP  API ，您可以在單一節點和 HA 組態中重新命名和刪除儲存 VM 。

.開始之前
Connector 需要特定權限來管理 Cloud Volumes ONTAP 的儲存 VM 。所需的權限包含在 https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-azure.html["NetApp 提供的原則"^]中。



=== 重新命名儲存VM

若要重新命名儲存 VM ，您應該提供現有儲存 VM 和新儲存 VM 的名稱做為參數。

.步驟
* 使用下列 API 呼叫重新命名單一節點系統上的儲存 VM ：
+
`PUT /azure/vsa/working-environments/{workingEnvironmentId}/svm`

+
在要求主體中包含下列參數：

+
[source, json]
----
{
  "svmNewName": "NewSvmName",
  "svmName": "OldSvmName"
}
----
* 使用下列 API 呼叫重新命名 HA 配對上的儲存 VM ：
+
`PUT /azure/ha/working-environments/{workingEnvironmentId}/svm`

+
在要求主體中包含下列參數：

+
[source, json]
----
{
  "svmNewName": "NewSvmName",
  "svmName": "OldSvmName"
}
----




=== 刪除儲存VM

在單一節點或 HA 組態中，如果儲存 VM 沒有任何作用中的 Volume ，您可以移除該 VM 。

.步驟
* 使用下列 API 呼叫來刪除單一節點系統上的儲存 VM ：
+
`DELETE /azure/vsa/working-environments/{workingEnvironmentId}/svm/{svmName}`

* 使用下列 API 呼叫刪除 HA 配對上的儲存 VM ：
+
`DELETE /azure/ha/working-environments/{workingEnvironmentId}/svm/{svmName}`



.相關資訊
* https://docs.netapp.com/us-en/bluexp-automation/cm/prepare.html["準備使用API"^]
* https://docs.netapp.com/us-en/bluexp-automation/cm/workflow_processes.html#organization-of-cloud-volumes-ontap-workflows["Cloud Volumes ONTAP 工作流程"^]

