---
sidebar: sidebar 
permalink: task-google-key-manager.html 
keywords: google cloud, encryption, NVE, NetApp volume encryption, KMIP, GCP, GCP KMS, key manager service, encryption 
summary: 利用 Google 的金鑰管理服務來提供第三方金鑰管理服務。 
---
= 使用 Google Cloud KMS 管理 Cloud Volumes ONTAP 加密金鑰
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
您可以在部署 Google Cloud Platform 的應用程式中，使用來link:https://cloud.google.com/kms/docs["Google Cloud Platform的金鑰管理服務（雲端KMS）"^]保護您的 Cloud Volumes ONTAP 加密金鑰。

您可以使用 ONTAP CLI 或 ONTAP REST API 來啟用雲端 KMS 的金鑰管理。

使用 Cloud KMS 時、請注意、根據預設、會使用 Data SVM 的 LIF 與雲端金鑰管理端點通訊。節點管理網路用於與雲端供應商的驗證服務（oauth2.googleapis.com）進行通訊。如果叢集網路設定不正確、叢集將無法正確使用金鑰管理服務。

.開始之前
* 您的系統應該運行 Cloud Volumes ONTAP 9.10.1 或更高版本
* 您必須使用資料 SVM。 CloudKMS 只能在資料 SVM 上配置。
* 您必須是叢集或SVM管理員
* 應在 SVM 上安裝磁碟區加密 (VE) 許可證
* 從 Cloud Volumes ONTAP 9.12.1 GA 開始，也應安裝多租戶加密金鑰管理 (MTEKM) 許可證
* 需要有效的 Google Cloud Platform 訂閱




== 組態

.Google Cloud
. 在您的Google Cloud環境中、 link:https://cloud.google.com/kms/docs/creating-keys["建立對稱的GCP金鑰環和金鑰"^]。
. 為 Cloud KMS 金鑰和 Cloud Volumes ONTAP 服務帳戶指派自訂角色。
+
.. 建立自訂角色：
+
[listing]
----
gcloud iam roles create kmsCustomRole
    --project=<project_id>
    --title=<kms_custom_role_name>
    --description=<custom_role_description>
    --permissions=cloudkms.cryptoKeyVersions.get,cloudkms.cryptoKeyVersions.list,cloudkms.cryptoKeyVersions.useToDecrypt,cloudkms.cryptoKeyVersions.useToEncrypt,cloudkms.cryptoKeys.get,cloudkms.keyRings.get,cloudkms.locations.get,cloudkms.locations.list,resourcemanager.projects.get
    --stage=GA
----
.. 指派您建立的自訂角色： 
`gcloud kms keys add-iam-policy-binding _key_name_ --keyring _key_ring_name_ --location _key_location_ --member serviceAccount:_service_account_Name_ --role projects/_customer_project_id_/roles/kmsCustomRole`
+

NOTE: 如果您使用的是 Cloud Volumes ONTAP 9.13.0 或更高版本，則無需建立自訂角色。您可以指派預定義的[`cloudkms.cryptoKeyEncrypterDecrypter` ^] 角色。



. 下載服務帳戶Json金鑰：「gCloud iam服務帳戶金鑰可建立金鑰檔案-iam-account=_sa-name_@_project-id_.iam.gserviceaccount.com」


.Cloud Volumes ONTAP
. 使用您偏好的SSH用戶端連線至叢集管理LIF。
. 切換至進階權限等級：「et -priv榮幸 進階」
. 為資料SVM建立DNS。「建立網域C_<project >_.internal -name-servers _server_address_-vserver _Svm_name_」
. 建立CMEK項目：「安全金鑰管理程式外部GCP啟用-vserver _Svm_name_-project -id _project _-key-ring_name _key_ring_name_-key-ring_location _key_ring_stip_-key-name _key_name_」
. 出現提示時、請從GCP帳戶輸入服務帳戶Json金鑰。
. 確認啟用的程序成功：「安全金鑰管理程式外部GCP檢查-vserver _svm_name_」
. 選用：建立磁碟區以測試加密「volvol create _volvolvole_name_-Aggregate _Aggregate _-vserver _vserver_name_-size 10G」




== 疑難排解

如果您需要疑難排解、可以跳接上述最後兩個步驟中的原始REST API記錄：

. "以d為準"
. "ystemShell -node_node_-command tail -f /mroot/etc/log/mlog/kmip2_client.log"

